name: Multi Jobs Workflow

on:
  workflow_dispatch:

jobs:
  multi-jobs-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First Workflow Job
        run: |
          echo "Hello, First Workflow!"


  second-workflow-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Second Workflow New Job 
        run: |
          echo "Hello, Second Workflow!"
